export const AUTHENTICATION_MODULE_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_SETTINGS_TOKEN';

export const ROCKETS_AUTH_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN =
  'ROCKETS_AUTH_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN';

export const AUTHENTICATION_MODULE_VALIDATE_TOKEN_SERVICE_TOKEN =
  'AUTHENTICATION_MODULE_VALIDATE_TOKEN_SERVICE_TOKEN';

export const AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN =
  'AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN';

export const ROCKETS_AUTH_MODULE_OPTIONS_TOKEN =
  'ROCKETS_AUTH_MODULE_OPTIONS_TOKEN';

export const ROCKETS_AUTH_MODULE_USER_LOOKUP_SERVICE_TOKEN =
  'ROCKETS_AUTH_MODULE_USER_LOOKUP_SERVICE_TOKEN';

export const RocketsAuthEmailService = Symbol(
  '__ROCKETS_AUTH_EMAIL_SERVICE_TOKEN__',
);

export const RocketsAuthUserModelService = Symbol(
  '__ROCKETS_AUTH_USER_LOOKUP_TOKEN__',
);

// Admin CRUD Service Token
export const ADMIN_USER_CRUD_SERVICE_TOKEN = Symbol(
  '__ADMIN_USER_CRUD_SERVICE_TOKEN__',
);
