export const ROCKETS_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN =
  'ROCKETS_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN';

export const ROCKETS_MODULE_OPTIONS_TOKEN = 'ROCKETS_MODULE_OPTIONS_TOKEN';

export const RocketsAuthProvider = Symbol('ROCKETS_AUTH_PROVIDER');
